databases:
  - name: eurotarde-db
    plan: free
    databaseName: eurotarde
    user: eurotarde

services:
  - type: web
    name: eurotarde
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ***REDACTED***
        value: ***REDACTED***
      - key: DATABASE_URL
        value: postgresql://eurotarde_user:zl2MlWeJ0Y5lAMGMZnicBehHMduaCEcg@dpg-d9ec01mrnols73dvfeo0-a.oregon-postgres.render.com/eurotarde
      - key: ADMIN_DEFAULT_USERNAME
        value: admin
      - key: ADMIN_DEFAULT_PASSWORD
        value: ***REDACTED***
      - key: DRAW_UPDATE_HOUR
        value: "0"
      - key: DRAW_UPDATE_MINUTE
        value: "0"
      - key: SESSION_MAX_AGE
        value: "3600"
